# Generated by Django 5.2.6 on 2025-12-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoQuienesSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Quienes Somos', max_length=200)),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen principal', null=True)),
                ('imagen_archivo', models.ImageField(blank=True, help_text='O subir una imagen desde el ordenador', null=True, upload_to='contenido/')),
                ('historia_titulo', models.CharField(default='Nuestra Historia', max_length=200)),
                ('historia_texto', models.TextField()),
                ('mision_titulo', models.CharField(default='Nuestra Misión', max_length=200)),
                ('mision_texto', models.TextField()),
                ('valores_titulo', models.CharField(default='Nuestros Valores', max_length=200)),
                ('valores', models.JSONField(default=list, help_text='Lista de valores en formato JSON')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido Quienes Somos',
                'verbose_name_plural': 'Contenido Quienes Somos',
            },
        ),
        migrations.CreateModel(
            name='ContenidoServiciosTerapeuticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Servicios Terapéuticos', max_length=200)),
                ('subtitulo', models.CharField(default='Masajes y terapias naturales para tu bienestar integral', max_length=300)),
                ('servicios', models.JSONField(default=list, help_text='Lista de servicios en formato JSON')),
                ('mensaje_agenda_titulo', models.CharField(default='Agenda Tu Sesión', max_length=200)),
                ('mensaje_agenda_texto', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido Servicios Terapéuticos',
                'verbose_name_plural': 'Contenido Servicios Terapéuticos',
            },
        ),
        migrations.CreateModel(
            name='EstacionHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(choices=[('invierno', 'Invierno'), ('primavera', 'Primavera'), ('verano', 'Verano'), ('otoño', 'Otoño')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen', null=True)),
                ('imagen_archivo', models.ImageField(blank=True, help_text='O subir una imagen desde el ordenador', null=True, upload_to='estaciones/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación Home',
                'verbose_name_plural': 'Estaciones Home',
                'ordering': ['estacion'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='oculto',
            field=models.BooleanField(default=False, help_text='Marcar para ocultar el producto del catálogo'),
        ),
        migrations.AddField(
            model_name='product',
            name='sin_stock',
            field=models.BooleanField(default=False, help_text='Marcar si el producto está sin stock'),
        ),
    ]
