# Generated by Django 5.2.6 on 2025-12-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_contenidoquienessomos_contenidoserviciosterapeuticos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='fas fa-spa', help_text='Clase de Font Awesome (ej: fas fa-hands)', max_length=100)),
                ('items', models.JSONField(blank=True, default=list, help_text="Lista de características del servicio (ej: ['Duración: 60 minutos', 'Reduce el estrés'])")),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar el servicio en la página')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio Terapéutico',
                'verbose_name_plural': 'Servicios Terapéuticos',
                'ordering': ['orden', 'created'],
            },
        ),
        migrations.RemoveField(
            model_name='contenidoserviciosterapeuticos',
            name='servicios',
        ),
    ]
