# Generated by Django 5.2.6 on 2025-12-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_servicioterapeutico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoBienvenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Bienvenido a Auka Terapias', max_length=200)),
                ('texto', models.TextField(default='Productos naturales para tu bienestar')),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen', null=True)),
                ('imagen_archivo', models.ImageField(blank=True, help_text='O subir una imagen desde el ordenador', null=True, upload_to='bienvenida/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foto de Bienvenida',
                'verbose_name_plural': 'Foto de Bienvenida',
            },
        ),
        migrations.DeleteModel(
            name='EstacionHome',
        ),
    ]
