# Generated by Django 5.2.6 on 2025-12-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_fotobienvenida_delete_estacionhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioterapeutico',
            name='color_icono',
            field=models.CharField(default='#667eea', help_text='Color del icono en formato hexadecimal (ej: #667eea)', max_length=7),
        ),
    ]
