# Generated by Django 5.2.6 on 2025-12-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_servicioterapeutico_color_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoquienessomos',
            name='historia_icono',
            field=models.CharField(default='fas fa-seedling', help_text='Icono para la sección Nuestra Historia', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidoquienessomos',
            name='historia_icono_color',
            field=models.CharField(default='#0d6efd', help_text='Color del icono para la sección Nuestra Historia', max_length=7),
        ),
        migrations.AddField(
            model_name='contenidoquienessomos',
            name='mision_icono',
            field=models.CharField(default='fas fa-heart', help_text='Icono para la sección Nuestra Misión', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidoquienessomos',
            name='mision_icono_color',
            field=models.CharField(default='#dc3545', help_text='Color del icono para la sección Nuestra Misión', max_length=7),
        ),
        migrations.AddField(
            model_name='contenidoquienessomos',
            name='titulo_icono',
            field=models.CharField(default='fas fa-leaf', help_text='Clase de Font Awesome para el icono del título principal', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidoquienessomos',
            name='titulo_icono_color',
            field=models.CharField(default='#198754', help_text='Color hexadecimal del icono del título principal', max_length=7),
        ),
        migrations.AddField(
            model_name='contenidoquienessomos',
            name='valores_icono',
            field=models.CharField(default='fas fa-certificate', help_text='Icono para la sección Nuestros Valores', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidoquienessomos',
            name='valores_icono_color',
            field=models.CharField(default='#0d6efd', help_text='Color del icono para la sección Nuestros Valores', max_length=7),
        ),
        migrations.AlterField(
            model_name='contenidoquienessomos',
            name='valores',
            field=models.JSONField(blank=True, default=list, help_text='Lista de valores en formato JSON'),
        ),
    ]
