# Generated by Django 5.2.6 on 2025-12-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_contenidoquienessomos_historia_icono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_navegador', models.CharField(default='Auka Terapias - Productos Naturales', help_text='Título que aparece en la pestaña del navegador', max_length=200)),
                ('favicon', models.ImageField(blank=True, help_text='Icono que aparece en la pestaña del navegador (recomendado: 32x32 o 16x16 píxeles)', null=True, upload_to='configuracion/')),
                ('texto_footer', models.TextField(default='Auka Terapias - Productos medicinales y cosméticos 100% naturales, cultivados con amor y dedicación para cuidar tu bienestar.', help_text='Texto que aparece en el footer del sitio')),
                ('url_instagram', models.URLField(blank=True, default='https://www.instagram.com/auka_terapias/?hl=es', help_text='URL de Instagram para el footer', null=True)),
                ('url_whatsapp_footer', models.URLField(blank=True, default='https://wa.me/56985661992', help_text='URL de WhatsApp para el footer (formato: https://wa.me/56985661992)', null=True)),
                ('numero_pedidos', models.CharField(default='+56985661992', help_text='Número de WhatsApp para recibir pedidos (formato: +56985661992)', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
