# Generated by Django 5.2.6 on 2025-12-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_configuracionsitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='nombre_navbar',
            field=models.CharField(default='AUKA', help_text='Nombre que aparece en la barra superior (navbar) junto al icono', max_length=100),
        ),
    ]
