# Generated by Django 5.2.6 on 2025-12-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_configuracionsitio_nombre_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Icono que aparece junto al nombre en la barra superior (navbar) (recomendado: 32x32 píxeles)', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='nombre_navbar',
            field=models.CharField(blank=True, default='AUKA', help_text='Nombre que aparece en la barra superior (navbar) junto al icono', max_length=100, null=True),
        ),
    ]
