# Generated by Django 5.2.6 on 2025-12-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_configuracionsitio_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='nombre_navbar',
            field=models.CharField(blank=True, default='AUKA', help_text='Nombre que aparece en la barra superior (navbar) junto al icono', max_length=100, null=True),
        ),
    ]
